counter = 5;
while counter != 0:
    counter -=1
    print("My name is Python....")

#Sample Output
# My name is Python....
# My name is Python....
# My name is Python....
# My name is Python....
# My name is Python....


